version: 2
jobs:
  build:
    docker:
      - image: endocrimes/kaniko-circle:latest
    steps:
      - checkout
      - run:
          name: Build docker image with kaniko
          command: |
            /kaniko/executor --dockerfile=Dockerfile \
              --destination=endocrimes/kaniko-test
